### ISSUE TITLE
Markers can be dragged outside of LineString Element

### ISSUE THREAD

**Issue by SirenHound** [w8r/L.Control.LineStringSelect#1]
There is an issue with creating a selection from the lineString, I have used your demo to illustrate.
Grabbing the marker and pulling it past the end of the segment extends the marker itself out to the point where the cursor influences the base feature. This influence (in latitude and longitude) becomes greater as the map is zoomed out.

I increased the thickness of the base feature to illustrate the discrepancy between its end and the end of the selection which was achieved at a lower zoom level.

![issue-lineselect](https://cloud.githubusercontent.com/assets/6420209/8299366/07905cb6-19aa-11e5-98ce-98108bf656d6.png)

**Comment by w8r** [comment]
@SirenHound, but I cannot drag it pass the end, how did you do that?

**Comment by SirenHound** [comment]
after I create a selection, the markers are draggable,
I can then drag the marker along the line, when it reaches the end of the line segment the marker is still dragged to the cursor location. Turning on the visual debugging shows that this only occurs to the extent of the cursors influence, however at lower zoom levels, the 'on the ground' influence of the cursor is increased, making it possible to drag the marker way off the end of the line segment.
I am running Google Chrome 'Version 43.0.2357.130 m' on Windows 7 Professional.

**Comment by w8r** [comment]
@SirenHound I see what you mean, not to the extent you described, but anyway it's weird. I'll look into that

**Comment by w8r** [comment]
Adopted your changes, thanks!
