### ISSUE TITLE
Dist files diasappeared

### ISSUE THREAD

**Issue by konradziczek** [w8r/L.Control.LineStringSelect#25]
Hello @w8r @Oliv
there are no dist files in /dist directory. When I browse commit history, there was .min.js file in the past, for example here:
https://github.com/w8r/L.Control.LineStringSelect/blob/a3f16b868a0de130a9c81c0a323ea1ce00c275f8/dist/L.Control.LineStringSelect.min.js

**Comment by w8r** [comment]
Yes, I killed them, it was always a bad practice to keep built code in git. You can find it in popular CDN services, like JSDelivr https://cdn.jsdelivr.net/npm/leaflet-linestring-select@1.1.1/dist/ or unpkg
