### ISSUE TITLE
Why is this a 'Control'?

### ISSUE THREAD

**Issue by SirenHound** [w8r/L.Control.LineStringSelect#4]
It seems that this class would fit better under L.Handler, since it is enabled/disabled and uses markers (much like the Draw handlers), and isn't added to a control corner (like other L.Control types)

Is there a reason that this wasn't extended from L.Handler?

**Comment by w8r** [comment]
Can be a handler, true, it almost doesn't have a UI. I don't know whether I would convert it though, since it has `Control` in it's name.
