### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by dmanjava** [w8r/L.Control.LineStringSelect#5]
Hello,
 Nice work!!! This is a really cool component.  I am developing a custom map tool in Angular2/4 project and would like to include your tool.  I am having issue getting it to load in my angular project (Typescript).  Do you have any Typescript support or recommendations for type script support and including and using in an Angular2/4 project?

Thank you in advance.

**Comment by ToHold** [comment]
Did you succes to use this plugin with leaflet 1.3.1 ?

**Comment by w8r** [comment]
Hi, I migrated the plugin to leaflet@1.5.x. If you know how to write `d.ts` files for leaflet plugins, any help would be welcome

**Comment by w8r** [comment]
I added TS support in v1.1.0
